# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0002_cuenta_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='padre',
            field=models.BooleanField(default=True),
        ),
    ]
