# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0003_auto_20181202_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=100)),
                ('sueldoBase', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ingresoExtra', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totalDevengado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('isss', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('afp', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('otrasDeducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sueldoLiquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
