# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0004_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
