# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0005_planilla_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(default='Admon', max_length=30),
        ),
    ]
